### ISSUE TITLE
[TRACKING] Adapter toplist (sorted)

### ISSUE THREAD

**Issue by mcm1957** [iobroker-community-adapters/responsive-design-initiative#4]
List of adapters registered at LATEST repository sorted by user count:

- [ ] `  rank` `  user` `adapter                       ` 
- [x] `     1` ` 76024` `js-controller                 `
- [ ] `     2` ` 72900` `admin                         `  
- [ ] `     3` ` 69775` `discovery                     `
- [x] `     4` ` 66818` `backitup                      `
- [ ] `     5` ` 55469` `javascript                    `
- [ ] `     6` ` 54575` `web                           `
- [x] `     7` ` 39961` `vis                           `
- [ ] `     8` ` 39958` `socketio                      `
- [x] `     9` ` 37929` `ws                            `
- [ ] `    10` ` 35163` `simple-api                    `
- [x] `    11` ` 29197` `shelly                        `
- [x] `    12` ` 28596` `history                       `
- [ ] `    13` ` 27307` `mqtt                          `
- [x] `    14` ` 22368` `ping                          `
- [x] `    15` ` 21455` `influxdb                      `
- [x] `    16` ` 20513` `alexa2                        `
- [ ] `    17` ` 19907` `tr-064                        `
- [x] `    18` ` 19439` `sonoff                        `
- [ ] `    19` ` 19155` `vis-hqwidgets                 `
- [x] `    20` ` 18370` `telegram                      `
- [ ] `    21` ` 17494` `hm-rpc                        `
- [ ] `    22` ` 17314` `vis-timeandweather            `
- [ ] `    23` ` 17154` `iot                           `
- [ ] `    24` ` 16674` `cloud                         `
- [x] `    25` ` 16536` `ical                          `
- [ ] `    26` ` 16456` `hm-rega                       `
- [ ] `    27` ` 16202` `flot                          `
- [ ] `    28` ` 15095` `modbus                        `
- [x] `    29` ` 14803` `zigbee                        `
- [ ] `    30` ` 14056` `node-red                      `
- [ ] `    31` ` 13873` `jarvis                        `
- [ ] `    32` ` 13482` `vis-inventwo                  `
- [ ] `    33` ` 12628` `daswetter                     `
- [ ] `    34` ` 12281` `hue                           `
- [ ] `    35` ` 12194` `fritzdect                     `
- [ ] `    36` ` 11870` `vis-2                         `
- [ ] `    37` ` 11421` `vis-metro                     `
- [ ] `    38` ` 11173` `icons-mfd-svg                 `
- [ ] `    39` ` 10994` `trashschedule                 `
- [x] `    40` ` 10801` `rpi2                          `
- [ ] `    41` ` 10795` `vis-jqui-mfd                  `
- [ ] `    42` ` 10562` `vis-icontwo                   `
- [x] `    43` ` 10555` `dwd                           `
- [ ] `    44` ` 10129` `tuya                          `
- [ ] `    45` `  9683` `devices                       `
- [ ] `    46` `  9677` `echarts                       `
- [ ] `    47` `  9397` `yahka                         `
- [ ] `    48` `  9366` `scenes                        `
- [x] `    49` `  9168` `net-tools                     `
- [ ] `    50` `  8950` `iqontrol                      `
- [ ] `    51` `  8815` `vis-bars                      `
- [x] `    52` `  8806` `email                         `
- [x] `    53` `  8763` `sql                           `
- [ ] `    54` `  8654` `tankerkoenig                  `
- [ ] `    55` `  8584` `vis-fancyswitch               `
- [ ] `    56` `  8540` `vis-weather                   `
- [ ] `    57` `  8454` `vis-justgage                  `
- [x] `    58` `  8225` `pushover                      `
- [ ] `    59` `  8197` `text2command                  `
- [ ] `    60` `  7909` `icons-mfd-png                 `
- [ ] `    61` `  7822` `vis-history                   `
- [ ] `    62` `  7588` `vis-material-advanced         `
- [ ] `    63` `  7508` `vis-colorpicker               `
- [ ] `    64` `  7375` `vis-materialdesign            `
- [ ] `    65` `  7355` `weatherunderground            `
- [ ] `    66` `  7199` `vis-canvas-gauges             `
- [ ] `    67` `  6877` `feiertage                     `
- [x] `    68` `  6826` `mqtt-client                   `
- [ ] `    69` `  6724` `openweathermap                `
- [ ] `    70` `  6680` `synology                      `
- [ ] `    71` `  6576` `sonos                         `
- [ ] `    72` `  6511` `alias-manager                 `
- [x] `    73` `  6408` `deconz                        `
- [ ] `    74` `  6329` `icons-ultimate-png            `
- [ ] `    75` `  6303` `whatsapp-cmb                  `
- [ ] `    76` `  6221` `icons-icons8                  `
- [ ] `    77` `  6012` `mihome-vacuum                 `
- [x] `    78` `  5797` `pvforecast                    `
- [ ] `    79` `  5730` `fb-checkpresence              `
- [ ] `    80` `  5652` `fullybrowser                  `
- [ ] `    81` `  5620` `smartmeter                    `
- [ ] `      ` `  5620` `hmip                          `
- [ ] `    83` `  5494` `habpanel                      `
- [x] `    84` `  5480` `homeconnect                   `
- [x] `    85` `  5435` `icons-material-png            `
- [ ] `    86` `  5365` `vis-plumb                     `
- [ ] `    87` `  5207` `vis-rgraph                    `
- [x] `    88` `  5123` `energiefluss                  `
- [ ] `    89` `  5036` `sourceanalytix                `
- [ ] `    90` `  4958` `wled                          `
- [ ] `    91` `  4935` `icons-open-icon-library-png   `
- [ ] `    92` `  4779` `device-reminder               `
- [ ] `    93` `  4719` `chromecast                    `
- [ ] `    94` `  4621` `lovelace                      `
- [ ] `    95` `  4598` `unifi                         `
- [ ] `    96` `  4553` `vis-2-widgets-material        `
- [ ] `    97` `  4538` `terminal                      `
- [ ] `    98` `  4194` `icons-addictive-flavour-png   `
- [ ] `    99` `  4168` `vis-players                   `
- [ ] `   100` `  4139` `accuweather                   `
- [ ] `   101` `  4131` `proxmox                       `
- [ ] `   102` `  4090` `vis-map                       `
- [ ] `   103` `  4010` `harmony                       `
- [ ] `   104` `  3928` `vis-2-widgets-energy          `
- [ ] `   105` `  3901` `sayit                         `
- [ ] `   106` `  3833` `vis-google-fonts              `
- [ ] `   107` `  3740` `onvif                         `
- [ ] `   108` `  3678` `netatmo                       `
- [x] `   109` `  3665` `shuttercontrol                `
- [x] `   110` `  3663` `worx                          `
- [ ] `   111` `  3572` `vis-2-widgets-gauges          `
- [x] `   112` `  3547` `icons-material-svg            `
- [x] `   113` `  3473` `energiefluss-erweitert        `
- [ ] `   114` `  3472` `mobile                        `
- [ ] `   115` `  3464` `vw-connect                    `
- [ ] `   116` `  3451` `samsung                       `
- [ ] `   117` `  3429` `parser                        `
- [ ] `   118` `  3410` `fronius                       `
- [ ] `   119` `  3394` `fritzbox                      `
- [ ] `   120` `  3284` `yr                            `
- [ ] `   121` `  3274` `lgtv                          `
- [x] `   122` `  3273` `statistics                    `
- [ ] `   123` `  3230` `broadlink2                    `
- [ ] `   124` `  3132` `icons-fatcow-hosting          `
- [ ] `   125` `  3104` `knx                           `
- [ ] `   126` `  2960` `material                      `
- [ ] `   127` `  2934` `ble                           `
- [ ] `   128` `  2839` `pollenflug                    `
- [ ] `   129` `  2830` `nina                          `
- [ ] `   130` `  2818` `hass                          `
- [ ] `   131` `  2817` `openknx                       `
- [ ] `   132` `  2783` `spotify-premium               `
- [ ] `   133` `  2766` `denon                         `
- [ ] `   134` `  2740` `vis-lcars                     `
- [x] `   135` `  2719` `upnp                          `
- [ ] `   136` `  2706` `ham                           `
- [ ] `   137` `  2640` `meross                        `
- [ ] `   138` `  2621` `smartthings                   `
- [ ] `   139` `  2589` `homekit-controller            `
- [x] `   140` `  2561` `tibberlink                    `
- [ ] `   141` `  2535` `radar2                        `
- [ ] `   142` `  2524` `mihome                        `
- [ ] `   143` `  2522` `vis-material                  `
- [x] `   144` `  2505` `followthesun                  `
- [x] `   145` `  2502` `zigbee2mqtt                   `
- [ ] `   146` `  2434` `tradfri                       `
- [ ] `   147` `  2401` `octoprint                     `
- [ ] `   148` `  2396` `reolink                       `
- [ ] `   149` `  2389` `vis-keyboard                  `
- [ ] `   150` `  2321` `viessmannapi                  `
- [ ] `   151` `  2297` `firetv                        `
- [ ] `   152` `  2272` `linux-control                 `
- [ ] `   153` `  2265` `pi-hole                       `
- [ ] `   154` `  2221` `nut                           `
- [ ] `   155` `  2203` `s7                            `
- [ ] `   156` `  2190` `nuki-extended                 `
- [x] `   157` `  2169` `ring                          `
- [ ] `      ` `  2169` `fhem                          `
- [ ] `   159` `  2168` `wifilight                     `
- [ ] `   160` `  2167` `smartgarden                   `
- [x] `   161` `  2159` `opendtu                       `
- [ ] `   162` `  2158` `heatingcontrol                `
- [ ] `   163` `  2143` `fullcalendar                  `
- [x] `   164` `  2125` `awtrix-light                  `
- [ ] `   165` `  2094` `hs100                         `
- [ ] `   166` `  2068` `systeminfo                    `
- [ ] `   167` `  2039` `linkeddevices                 `
- [x] `   168` `  2024` `sma-em                        `
- [ ] `   169` `  2011` `mielecloudservice             `
- [x] `   170` `  1980` `alarm                         `
- [ ] `   171` `  1976` `go-e                          `
- [ ] `   172` `  1955` `bshb                          `
- [x] `   173` `  1945` `roborock                      `
- [ ] `   174` `  1940` `snmp                          `
- [ ] `   175` `  1937` `bring                         `
- [ ] `   176` `  1908` `loxone                        `
- [x] `   177` `  1905` `schoolfree                    `
- [ ] `   178` `  1895` `netatmo-crawler               `
- [x] `   179` `  1878` `device-watcher                `
- [ ] `   180` `  1825` `ecovacs-deebot                `
- [ ] `   181` `  1816` `fronius-solarweb              `
- [ ] `   182` `  1780` `signal-cmb                    `
- [ ] `   183` `  1759` `smartcontrol                  `
- [ ] `   184` `  1656` `plenticore                    `
- [ ] `   185` `  1628` `vis-2-widgets-jaeger-design   `
- [ ] `   186` `  1619` `notification-manager          `
- [x] `   187` `  1613` `growatt                       `
- [ ] `   188` `  1599` `tapo                          `
- [ ] `   189` `  1594` `tesla-motors                  `
- [ ] `      ` `  1594` `nuki                          `
- [ ] `   191` `  1580` `eusec                         `
- [ ] `   192` `  1574` `evcc                          `
- [ ] `   193` `  1525` `bydhvs                        `
- [x] `   194` `  1473` `tado                          `
- [ ] `   195` `  1445` `bmw                           `
- [ ] `   196` `  1436` `vis-2-widgets-inventwo        `
- [ ] `   197` `  1433` `doorbird                      `
- [ ] `   198` `  1430` `roomba                        `
- [ ] `   199` `  1429` `luftdaten                     `
- [x] `   200` `  1409` `deyeidc                       `
- [x] `   201` `  1401` `ems-esp                       `
- [ ] `   202` `  1400` `yeelight-2                    `
- [ ] `   203` `  1391` `sony-bravia                   `
- [ ] `   204` `  1390` `cameras                       `
- [ ] `   205` `  1382` `solarwetter                   `
- [x] `   206` `  1376` `logparser                     `
- [ ] `   207` `  1369` `tahoma                        `
- [ ] `   208` `  1346` `solarmanpv                    `
- [x] `   209` `  1337` `lg-thinq                      `
- [ ] `   210` `  1332` `moma                          `
- [x] `   211` `  1325` `birthdays                     `
- [ ] `   212` `  1310` `coronavirus-statistics        `
- [ ] `   213` `  1256` `zwave2                        `
- [ ] `   214` `  1251` `rest-api                      `
- [ ] `   215` `  1216` `esphome                       `
- [ ] `   216` `  1203` `gruenbeck                     `
- [ ] `   217` `  1175` `sainlogic                     `
- [ ] `   218` `  1163` `onkyo                         `
- [ ] `   219` `  1148` `vis-material-webfont          `
- [ ] `   220` `  1132` `powerfox2                     `
- [ ] `   221` `  1117` `time-switch                   `
- [ ] `   222` `  1096` `yamaha                        `
- [x] `   223` `  1085` `enigma2                       `
- [ ] `   224` `  1082` `mercedesme                    `
- [ ] `   225` `  1070` `rickshaw                      `
- [ ] `   226` `  1066` `bosesoundtouch                `
- [ ] `   227` `  1065` `daikin                        `
- [ ] `   228` `  1054` `musiccast                     `
- [ ] `   229` `  1053` `kodi                          `
- [ ] `   230` `  1049` `samsung_tizen                 `
- [ ] `   231` `  1040` `midea                         `
- [x] `   232` `  1034` `e3dc-rscp                     `
- [ ] `   233` `  1031` `operating-hours               `
- [ ] `   234` `  1029` `virtualpowermeter             `
- [x] `   235` `  1021` `govee-local                   `
- [ ] `   236` `  1019` `awattar                       `
- [ ] `   237` `  1006` `tvspielfilm                   `
- [ ] `   238` `   972` `windows-control               `
- [x] `   239` `   964` `ds18b20                       `
- [ ] `   240` `   951` `heizoel                       `
- [x] `   241` `   938` `heos                          `
- [ ] `      ` `   938` `daikin-cloud                  `
- [x] `   243` `   935` `klf200                        `
- [ ] `   244` `   926` `plex                          `
- [ ] `   245` `   919` `parcel                        `
- [ ] `      ` `   919` `countdown                     `
- [ ] `   247` `   905` `geofency                      `
- [ ] `   248` `   904` `telegram-menu                 `
- [ ] `   249` `   895` `bluelink                      `
- [x] `   250` `   894` `sun2000                       `
- [ ] `   251` `   891` `semp                          `
- [ ] `   252` `   887` `fahrplan                      `
- [ ] `   253` `   869` `easee                         `
- [ ] `   254` `   832` `ebus                          `
- [x] `   255` `   829` `melcloud                      `
- [x] `   256` `   812` `adguard                       `
- [ ] `   257` `   809` `sbfspot                       `
- [ ] `   258` `   793` `minuvis                       `
- [ ] `   259` `   778` `philips-tv                    `
- [ ] `   260` `   774` `vaillant                      `
- [x] `   261` `   771` `kecontact                     `
- [ ] `   262` `   754` `senec                         `
- [x] `   263` `   741` `solarlog                      `
- [x] `   264` `   732` `solax                         `
- [x] `   265` `   725` `viessmann                     `
- [ ] `      ` `   725` `solaredge                     `
- [ ] `   267` `   724` `cul                           `
- [ ] `   268` `   719` `openhab                       `
- [ ] `   269` `   716` `meteoalarm                    `
- [ ] `   270` `   696` `robonect                      `
- [ ] `   271` `   689` `sonnen                        `
- [ ] `   272` `   686` `panasonic-viera               `
- [ ] `      ` `   686` `nanoleaf-lightpanels          `
- [ ] `   274` `   685` `tronity                       `
- [ ] `      ` `   685` `mbus                          `
- [ ] `   276` `   682` `valuetrackerovertime          `
- [ ] `   277` `   681` `bosch-ebike                   `
- [x] `   278` `   676` `alexa-timer-vis               `
- [ ] `   279` `   674` `withings                      `
- [x] `      ` `   674` `rssfeed                       `
- [x] `   281` `   669` `frontier_silicon              `
- [ ] `   282` `   653` `proxy                         `
- [ ] `   283` `   643` `mihome-cloud                  `
- [ ] `   284` `   642` `welcome                       `
- [x] `      ` `   642` `pegelalarm                    `
- [ ] `   286` `   639` `bydbatt                       `
- [ ] `   287` `   637` `innogy-smarthome              `
- [ ] `   288` `   634` `sprinklecontrol               `
- [x] `   289` `   632` `odl                           `
- [ ] `   290` `   623` `fakeroku                      `
- [ ] `   291` `   618` `fronius-wattpilot             `
- [x] `   292` `   615` `squeezeboxrpc                 `
- [x] `   293` `   608` `tvprogram                     `
- [ ] `      ` `   608` `renault                       `
- [ ] `   295` `   605` `stiebel-isg                   `
- [ ] `   296` `   598` `acme                          `
- [ ] `   297` `   595` `eventlist                     `
- [x] `   298` `   578` `dysonairpurifier              `
- [ ] `   299` `   577` `maxcube                       `
- [ ] `   300` `   569` `velux                         `
- [ ] `   301` `   568` `scheduler                     `
- [ ] `   302` `   566` `vis-homekittiles              `
- [ ] `   303` `   553` `i2c                           `
- [ ] `   304` `   549` `icons-smarthome               `
- [ ] `   305` `   548` `milight                       `
- [ ] `   306` `   542` `homee                         `
- [x] `      ` `   542` `apcups                        `
- [ ] `   308` `   537` `residents                     `
- [ ] `   309` `   536` `xterm                         `
- [ ] `   310` `   517` `ocpp                          `
- [ ] `   311` `   513` `milight-smart-light           `
- [ ] `   312` `   510` `pushsafer                     `
- [ ] `   313` `   509` `asterisk                      `
- [ ] `   314` `   508` `paw                           `
- [ ] `   315` `   507` `zendure-solarflow             `
- [ ] `      ` `   507` `owfs                          `
- [ ] `   317` `   495` `web-speedy                    `
- [ ] `   318` `   492` `wolf-smartset                 `
- [ ] `   319` `   491` `icons-freepic                 `
- [x] `      ` `   491` `alpha-ess                     `
- [x] `   321` `   490` `mytime                        `
- [ ] `   322` `   487` `owntracks                     `
- [ ] `   323` `   486` `unifi-protect                 `
- [x] `   324` `   482` `openligadb                    `
- [ ] `   325` `   481` `divera247                     `
- [x] `   326` `   478` `swiss-weather-api             `
- [ ] `   327` `   466` `sun2000-modbus                `
- [ ] `   328` `   458` `mystrom                       `
- [ ] `   329` `   454` `ford                          `
- [x] `   330` `   453` `alexa-shoppinglist            `
- [ ] `   331` `   449` `webuntis                      `
- [ ] `   332` `   447` `mpd                           `
- [ ] `   333` `   428` `places                        `
- [x] `   334` `   422` `fuelpricemonitor              `
- [ ] `      ` `   422` `drag-indicator                `
- [ ] `   336` `   411` `discovergy                    `
- [ ] `   337` `   410` `philips-air                   `
- [ ] `   338` `   400` `jeelink                       `
- [ ] `      ` `   400` `bambulab                      `
- [ ] `   340` `   393` `rflink                        `
- [ ] `   341` `   391` `icons-eclipse-smarthome-classic`
- [ ] `   342` `   388` `webcal                        `
- [ ] `      ` `   388` `twinkly                       `
- [x] `      ` `   388` `kostal-piko-ba                `
- [ ] `   345` `   382` `miele                         `
- [ ] `   346` `   381` `lametric                      `
- [x] `   347` `   378` `oilfox                        `
- [x] `   348` `   372` `panasonic-comfort-cloud       `
- [ ] `   349` `   366` `luxtronik2                    `
- [ ] `      ` `   366` `botvac                        `
- [ ] `   351` `   364` `wolf                          `
- [ ] `   352` `   361` `lightify                      `
- [ ] `   353` `   360` `weather-warnings              `
- [x] `      ` `   360` `traccar                       `
- [ ] `   355` `   356` `wiffi-wz                      `
- [ ] `   356` `   354` `enocean                       `
- [ ] `   357` `   344` `vis-2-widgets-sweethome3d     `
- [ ] `   358` `   342` `lgtv11                        `
- [ ] `      ` `   342` `iwg-vpn                       `
- [x] `   360` `   338` `uv-protect                    `
- [ ] `   361` `   336` `webui                         `
- [ ] `      ` `   336` `mclighting                    `
- [ ] `      ` `   336` `artnet                        `
- [ ] `   364` `   335` `vis-2-widgets-radar-trap      `
- [ ] `      ` `   335` `fiat                          `
- [ ] `   366` `   331` `lupusec                       `
- [ ] `   367` `   329` `wireguard                     `
- [ ] `      ` `   329` `garmin                        `
- [x] `   369` `   328` `tinymqttbroker                `
- [ ] `   370` `   325` `froeling                      `
- [ ] `   371` `   322` `weishaupt-wem                 `
- [ ] `   372` `   318` `lightcontrol                  `
- [ ] `   373` `   315` `calendar                      `
- [ ] `   374` `   314` `homepilot                     `
- [ ] `      ` `   314` `hikvision-alarmserver         `
- [ ] `   376` `   305` `wireless-mbus                 `
- [ ] `   377` `   303` `vesync                        `
- [ ] `   378` `   302` `myenergi                      `
- [ ] `   379` `   297` `wiobrowser                    `
- [ ] `   380` `   296` `link                          `
- [ ] `      ` `   296` `amazon-dash                   `
- [x] `   382` `   295` `apg-info                      `
- [ ] `   383` `   293` `pylontech                     `
- [ ] `   384` `   292` `vr200                         `
- [ ] `   385` `   291` `bidirectional-counter         `
- [ ] `   386` `   288` `g-homa                        `
- [ ] `   387` `   282` `mikrotik                      `
- [x] `   388` `   281` `sureflap                      `
- [ ] `      ` `   281` `meater                        `
- [ ] `      ` `   281` `bsblan                        `
- [ ] `   391` `   275` `ph803w                        `
- [ ] `      ` `   275` `beckhoff                      `
- [ ] `   393` `   272` `wallpanel                     `
- [ ] `   394` `   270` `smart-eq                      `
- [ ] `      ` `   270` `canbus                        `
- [ ] `   396` `   266` `ekey                          `
- [ ] `   397` `   263` `volvo                         `
- [ ] `   398` `   260` `youtube                       `
- [ ] `   399` `   258` `resol                         `
- [ ] `   400` `   255` `gira-iot                      `
- [ ] `   401` `   245` `valloxmv                      `
- [ ] `      ` `   245` `slideshow                     `
- [x] `   403` `   243` `ecoflow-mqtt                  `
- [x] `   404` `   239` `epson_ecotank_et_2750         `
- [x] `      ` `   239` `envertech-pv                  `
- [ ] `   406` `   236` `volumio                       `
- [ ] `      ` `   236` `espresense                    `
- [x] `   408` `   232` `discord                       `
- [ ] `   409` `   231` `maxcul                        `
- [ ] `   410` `   230` `hoover                        `
- [ ] `   411` `   229` `yahoo-stock-market            `
- [ ] `      ` `   229` `iceroad                       `
- [x] `   413` `   228` `rct                           `
- [ ] `   414` `   227` `emby                          `
- [x] `      ` `   227` `boschindego                   `
- [ ] `      ` `   227` `adb                           `
- [ ] `   417` `   223` `pushbullet                    `
- [ ] `   418` `   222` `ecoflow                       `
- [ ] `   419` `   221` `energymanager                 `
- [x] `   420` `   220` `myuplink                      `
- [ ] `   421` `   214` `airconwithme                  `
- [x] `   422` `   209` `imap                          `
- [ ] `   423` `   207` `judoisoft                     `
- [ ] `   424` `   206` `xbox                          `
- [ ] `      ` `   206` `nibeuplink                    `
- [ ] `      ` `   206` `doorio                        `
- [x] `   427` `   205` `myvbus                        `
- [ ] `      ` `   205` `frigate                       `
- [x] `   429` `   199` `solarviewdatareader           `
- [ ] `   430` `   196` `vedirect                      `
- [ ] `   431` `   195` `digitalstrom                  `
- [ ] `   432` `   189` `mysensors                     `
- [ ] `   433` `   187` `plexconnect                   `
- [ ] `      ` `   187` `hp-ilo                        `
- [ ] `      ` `   187` `comfoair                      `
- [ ] `   436` `   186` `loqed                         `
- [ ] `   437` `   183` `roadtraffic                   `
- [ ] `   438` `   180` `megaesp                       `
- [ ] `   439` `   178` `bwt                           `
- [ ] `   440` `   176` `pid                           `
- [ ] `      ` `   176` `miio                          `
- [ ] `   442` `   175` `hid-community                 `
- [ ] `      ` `   175` `bestway                       `
- [ ] `   444` `   174` `phantomjs                     `
- [ ] `   445` `   169` `hyperion_ng                   `
- [ ] `   446` `   168` `asuswrt                       `
- [ ] `   447` `   164` `heizungssteuerung             `
- [ ] `   448` `   162` `sia                           `
- [x] `   449` `   156` `signifylights                 `
- [ ] `   450` `   155` `lorawan                       `
- [ ] `   451` `   150` `synochat                      `
- [ ] `   452` `   148` `vis-2-widgets-weather-and-heating`
- [ ] `      ` `   148` `linktap                       `
- [ ] `   454` `   145` `vofo-speedtest                `
- [ ] `      ` `   145` `schwoerer-ventcube            `
- [ ] `   456` `   144` `fitbit-fitness                `
- [ ] `   457` `   140` `helios                        `
- [ ] `   458` `   138` `wlanthermo-nano               `
- [ ] `      ` `   138` `b-control-em                  `
- [ ] `   460` `   136` `rainbird                      `
- [ ] `   461` `   135` `vis-3dmodel                   `
- [ ] `   462` `   131` `lg-ess-home                   `
- [ ] `   463` `   130` `wireless-settings             `
- [ ] `      ` `   130` `mihome-airpurifier            `
- [ ] `      ` `   130` `hydrawise                     `
- [ ] `      ` `   130` `hass-mqtt                     `
- [ ] `   467` `   129` `zoe2                          `
- [ ] `      ` `   129` `mydlink                       `
- [ ] `      ` `   129` `ico-cloud                     `
- [ ] `   470` `   127` `luxtronik1                    `
- [ ] `   471` `   122` `pixelit                       `
- [x] `      ` `   122` `gotify                        `
- [ ] `   473` `   120` `smappee                       `
- [ ] `      ` `   120` `exchangerates                 `
- [ ] `   475` `   119` `puppeteer                     `
- [x] `      ` `   119` `nissan                        `
- [ ] `      ` `   119` `mihome-plug                   `
- [ ] `   478` `   118` `oekofen-json                  `
- [ ] `   479` `   117` `mediola-gateway               `
- [x] `   480` `   114` `matrix-org                    `
- [ ] `   481` `   113` `netatmo-energy                `
- [ ] `   482` `   106` `intex                         `
- [ ] `   483` `   104` `zehnder-cloud                 `
- [ ] `      ` `   104` `warp                          `
- [ ] `   485` `   103` `mihome-lamp                   `
- [ ] `   486` `   100` `radar-trap                    `
- [ ] `      ` `   100` `libre                         `
- [ ] `      ` `   100` `blebox                        `
- [ ] `   489` `    99` `janitza-gridvis               `
- [ ] `      ` `    99` `haassohn                      `
- [ ] `   491` `    97` `opcua                         `
- [ ] `   492` `    96` `stockmarket                   `
- [ ] `   493` `    95` `todoist2                      `
- [ ] `   494` `    93` `vds2465-server                `
- [ ] `      ` `    93` `lifx                          `
- [ ] `   496` `    91` `toyota                        `
- [ ] `      ` `    91` `tileboard                     `
- [ ] `   498` `    89` `snips                         `
- [ ] `      ` `    89` `alpha2                        `
- [ ] `   500` `    87` `vis-2-widgets-rssfeed         `
- [ ] `      ` `    87` `procon-ip                     `
- [ ] `      ` `    87` `lcn                           `
- [ ] `      ` `    87` `heizoel24-mex                 `
- [ ] `   504` `    84` `tedee                         `
- [ ] `      ` `    84` `knmi-weather                  `
- [x] `   506` `    83` `tractive-gps                  `
- [x] `   507` `    81` `wiegand-tcpip                 `
- [ ] `   508` `    80` `soliscloud                    `
- [ ] `   509` `    79` `enet                          `
- [ ] `   510` `    78` `cec2                          `
- [ ] `   511` `    76` `zoneminder                    `
- [ ] `      ` `    76` `amtronwallbox                 `
- [ ] `   513` `    75` `botslab360                    `
- [ ] `   514` `    72` `vis-2-widgets-ovarious        `
- [ ] `      ` `    72` `imow                          `
- [ ] `      ` `    72` `consumption                   `
- [ ] `   517` `    70` `notificationforandroidtv      `
- [ ] `   518` `    68` `hue-sync-box                  `
- [x] `      ` `    68` `gree-hvac                     `
- [ ] `   520` `    67` `xs1                           `
- [ ] `      ` `    67` `pvoutputorg                   `
- [ ] `      ` `    67` `porsche                       `
- [ ] `   523` `    66` `benchmark                     `
- [ ] `   524` `    65` `opi                           `
- [x] `   525` `    64` `tinker                        `
- [ ] `      ` `    64` `ham-wemo                      `
- [ ] `   527` `    63` `wmswebcontrol                 `
- [ ] `   528` `    62` `link2home                     `
- [x] `   529` `    61` `gsmsms                        `
- [ ] `   530` `    56` `haier                         `
- [ ] `      ` `    56` `contactid                     `
- [ ] `   532` `    54` `lowpass-filter                `
- [ ] `   533` `    53` `tesla-wallconnector3          `
- [ ] `      ` `    53` `smoothed                      `
- [ ] `      ` `    53` `pjlink                        `
- [ ] `   536` `    52` `emporia                       `
- [ ] `   537` `    51` `hiob                          `
- [x] `   538` `    50` `cloudflare                    `
- [ ] `   539` `    49` `niu                           `
- [ ] `      ` `    49` `myq                           `
- [ ] `   541` `    48` `xiaomi-gateway3               `
- [ ] `      ` `    48` `pimatic                       `
- [x] `      ` `    48` `e3oncan                       `
- [ ] `   544` `    46` `weatherflow_udp               `
- [ ] `      ` `    46` `huum-sauna                    `
- [ ] `   546` `    45` `lgtv-rs                       `
- [ ] `      ` `    45` `google-spreadsheet            `
- [ ] `   548` `    44` `selverf                       `
- [ ] `   549` `    43` `fenecon                       `
- [ ] `   550` `    42` `seq                           `
- [ ] `      ` `    42` `megadd                        `
- [ ] `      ` `    42` `benq                          `
- [ ] `      ` `    42` `anelhut                       `
- [ ] `   554` `    41` `wamo                          `
- [ ] `      ` `    41` `speedport                     `
- [x] `      ` `    41` `jablotron                     `
- [ ] `      ` `    41` `hausbus_de                    `
- [ ] `   558` `    38` `rfxcom                        `
- [ ] `   559` `    36` `multicast                     `
- [ ] `   560` `    35` `elgato-key-light              `
- [x] `   561` `    34` `egigeozone2                   `
- [ ] `   562` `    33` `starline                      `
- [ ] `      ` `    33` `siegenia                      `
- [ ] `      ` `    33` `mercury                       `
- [x] `   565` `    31` `renacidc                      `
- [ ] `      ` `    31` `hekr                          `
- [ ] `   567` `    29` `epson_stylus_px830            `
- [ ] `   568` `    28` `radiohead                     `
- [ ] `   569` `    27` `oppoplayer                    `
- [ ] `   570` `    26` `megad                         `
- [ ] `      ` `    26` `air-q                         `
- [x] `   572` `    25` `gotify-ws                     `
- [ ] `   573` `    24` `sensebox                      `
- [ ] `      ` `    24` `elero-usb-transmitter         `
- [ ] `   575` `    23` `airzone                       `
- [ ] `   576` `    22` `weblogin                      `
- [ ] `      ` `    22` `contact                       `
- [x] `   578` `    21` `heytech                       `
- [ ] `   579` `    20` `sonnen-charger                `
- [x] `      ` `    20` `nsclient                      `
- [ ] `      ` `    20` `foobar2000                    `
- [ ] `      ` `    20` `flexcharts                    `
- [x] `      ` `    20` `chargemaster                  `
- [ ] `   584` `    19` `waterkotte-easycon            `
- [ ] `      ` `    19` `teslamateapi                  `
- [ ] `      ` `    19` `seko                          `
- [ ] `      ` `    19` `hdg-bavaria                   `
- [ ] `   588` `    18` `micronova                     `
- [x] `   589` `    17` `ikettle2                      `
- [ ] `      ` `    17` `hilink                        `
- [ ] `   591` `    16` `nmea                          `
- [x] `   592` `    15` `kisshome-research             `
- [ ] `      ` `    15` `intesishome                   `
- [ ] `      ` `    15` `artnet-recorder               `
- [ ] `   595` `    14` `palazzetti                    `
- [ ] `      ` `    14` `opentherm                     `
- [ ] `      ` `    14` `iopooleco                     `
- [ ] `   598` `    13` `zont                          `
- [ ] `      ` `    13` `aio                           `
- [ ] `   600` `    12` `srm                           `
- [ ] `      ` `    12` `opensmartcity                 `
- [ ] `      ` `    12` `maveo                         `
- [ ] `      ` `    12` `corrently                     `
- [x] `   604` `    11` `voltoplus                     `
- [ ] `      ` `    11` `trivum                        `
- [ ] `      ` `    11` `piface                        `
- [ ] `   607` `     9` `tunnelbroker-endpoint-updater `
- [ ] `      ` `     9` `hombot                        `
- [ ] `   609` `     8` `x-touch                       `
- [ ] `      ` `     8` `minuaru                       `
- [ ] `      ` `     8` `googleauth                    `
- [ ] `   612` `     7` `tino                          `
- [x] `      ` `     7` `remeha-home                   `
- [ ] `      ` `     7` `homenet                       `
- [ ] `      ` `     7` `batrium-bms                   `
- [ ] `   616` `     6` `cleveron                      `
- [ ] `      ` `     6` `atlas-scientific-ezo-i2c      `
- [ ] `   618` `     5` `letrika_comgw                 `
- [ ] `   619` `     4` `sonus                         `
- [x] `      ` `     4` `innoxel                       `
- [ ] `      ` `     4` `bascloud                      `
- [ ] `   622` `     3` `sanext                        `
- [ ] `      ` `     3` `rmb-bhkw                      `
- [ ] `      ` `     3` `omron-fins                    `
- [ ] `      ` `     3` `netro                         `
- [ ] `      ` `     3` `legrand-ecocompteur           `
- [ ] `   627` `     2` `vbus-gw                       `
- [ ] `      ` `     2` `tinyrx4                       `
- [ ] `      ` `     2` `omnicomm-lls                  `
- [ ] `      ` `     2` `noolitef                      `
- [ ] `      ` `     2` `message-queue                 `
- [ ] `      ` `     2` `extron                        `
