### ISSUE TITLE
[TRACKING] Adapters *NOT* listed at repositories

### ISSUE THREAD

**Issue by mcm1957** [iobroker-community-adapters/responsive-design-initiative#5]
Folgende Adapter sind NICHT im Repository gelistet:

- [ ] `  rank` `  user` `adapter                       ` 
- [x] `     1` ` 19381` `info                          ` - DEPRECATED
- [x] `     2` `  3958` `hue-extended                  ` - DEPRECATED
- [ ] `     3` `   787` `vis-2-beta                    `
- [ ] `     4` `   664` `homepilot20                   `
- [ ] `     5` `   616` `apple-find-me                 `
- [x] `     6` `   585` `km200                         ` - DEPRECATED
- [ ] `     7` `   492` `switchbot-hub                 ` 
- [ ] `     8` `   469` `psa                           `
- [ ] `     9` `   451` `govee                         `
- [ ] `    10` `   370` `landroid                      `
- [ ] `    11` `   357` `govee-app                     `
- [ ] `    12` `   335` `tibberconnect                 `
- [ ] `    13` `   328` `find-my-iphone                `
- [ ] `    14` `   326` `life360                       `
- [ ] `    15` `   322` `sunnyportal                   `
- [ ] `    16` `   314` `husqvarna-automower           `
- [ ] `    17` `   312` `fusionsolar                   `
- [ ] `    18` `   290` `switchbot-ble                 `
- [ ] `    19` `   253` `binance                       `
- [ ] `    20` `   212` `goodwe                        `
- [ ] `    21` `   204` `klipper-moonraker             `
- [ ] `    22` `   193` `iogopro                       `
- [ ] `    23` `   192` `tibber                        `
- [ ] `    24` `   180` `apsystems-ecu                 `
- [ ] `    25` `   177` `squeezebox                    `
- [ ] `    26` `   170` `fully-tablet-control          `
- [ ] `    27` `   153` `mobile-alerts                 `
- [ ] `    28` `   150` `blink4home                    `
- [ ] `    29` `   147` `radar                         `
- [ ] `    30` `   144` `hyperion                      `
- [ ] `    31` `   143` `husq-automower                `
- [ ] `    32` `   141` `zwave                         `
- [ ] `    33` `   140` `blockly-plus                  `
- [ ] `    34` `   138` `egigeozone                    `
- [ ] `    35` `   137` `vis-owl                       `
- [ ] `    36` `   136` `hmm                           `
- [ ] `    37` `   133` `rtspstream                    `
- [ ] `    38` `   129` `js2fs                         `
- [ ] `    39` `   122` `iogo                          `
- [ ] `    40` `   119` `sma-speedwire                 `
- [ ] `    41` `   117` `omada                         `
- [ ] `    42` `   116` `gartenbewaesserung            `
- [ ] `    43` `   111` `matter                        `
- [ ] `    44` `   108` `blueconnect                   `
- [ ] `    45` `   103` `broadlink                     `
- [ ] `    46` `    97` `vuplus                        `
- [ ] `    47` `    96` `eufy-security                 `
- [ ] `    48` `    92` `comfoairq                     `
- [ ] `    49` `    91` `google-sharedlocations        `
- [ ] `    50` `    88` `tr-064-community              `
- [ ] `      ` `    88` `sma-ev-charger                `
- [ ] `    52` `    81` `labcom                        `
- [ ] `    53` `    79` `gree_aircon                   `
- [ ] `    54` `    78` `gardena                       `
- [ ] `      ` `    78` `freeathome                    `
- [ ] `      ` `    78` `euhome                        `
- [ ] `    57` `    74` `ap-systems-ez1                `
- [ ] `    58` `    73` `woso_mitsu_aircon_rac         `
- [ ] `      ` `    73` `repetierserver                `
- [ ] `      ` `    73` `dreame                        `
- [ ] `    61` `    71` `drops-weather                 `
- [ ] `    62` `    66` `wetty                         `
- [ ] `    63` `    65` `onvif-alt                     `
- [ ] `    64` `    64` `mystrom-wifi-switch           `
- [ ] `      ` `    64` `landroid-s                    `
- [ ] `    66` `    56` `vcard                         `
- [ ] `      ` `    56` `rtl_433                       `
- [ ] `    68` `    49` `rika-firenet                  `
- [ ] `      ` `    49` `etamon                        `
- [ ] `      ` `    49` `connector-local-control       `
- [ ] `    71` `    48` `mywallbox                     `
- [ ] `    72` `    47` `ve                            `
- [ ] `      ` `    47` `rtspStream                    `
- [ ] `    74` `    46` `samsung2016                   `
- [ ] `    75` `    44` `alexa                         `
- [ ] `    76` `    43` `eq3-thermostat                `
- [ ] `    77` `    42` `hpcontrol                     `
- [ ] `    78` `    40` `nest                          `
- [ ] `    79` `    39` `siro                          `
- [ ] `    80` `    38` `solaredge-modbus              `
- [ ] `      ` `    38` `megadd2                       `
- [ ] `    82` `    37` `pv-power-control              `
- [ ] `      ` `    37` `motionblinds                  `
- [ ] `      ` `    37` `controme                      `
- [ ] `    85` `    36` `vodafone-speedtest            `
- [ ] `      ` `    36` `pioneer_sc_vsx                `
- [ ] `    87` `    35` `pjlinkv2                      `
- [ ] `    88` `    33` `xplora                        `
- [ ] `      ` `    33` `repetier                      `
- [ ] `      ` `    33` `motion                        `
- [ ] `    91` `    30` `go-e-charger                  `
- [ ] `      ` `    30` `boscheasycontrol              `
- [ ] `    93` `    29` `vis-beta                      `
- [ ] `      ` `    29` `mieleathome                   `
- [ ] `    95` `    28` `samsung-community             `
- [ ] `      ` `    28` `pilight                       `
- [ ] `    97` `    27` `openwrt                       `
- [ ] `      ` `    27` `google-smart-home-fulfillment `
- [ ] `    99` `    26` `nuki2                         `
- [ ] `   100` `    25` `pioneer                       `
- [ ] `      ` `    25` `nctalk                        `
- [ ] `      ` `    25` `gigaset-elements              `
- [ ] `      ` `    25` `apsystemsez1                  `
- [ ] `   104` `    24` `scheppach-roboticmower        `
- [ ] `      ` `    24` `fontui                        `
- [ ] `      ` `    24` `fitbit-api                    `
- [ ] `      ` `    24` `ankersolix2                   `
- [ ] `   108` `    23` `evohome                       `
- [ ] `   109` `    22` `pbx-3cx                       `
- [ ] `      ` `    22` `hueemu                        `
- [ ] `      ` `    22` `bjfreeathome                  `
- [ ] `   112` `    21` `yeelight                      `
- [ ] `   113` `    20` `powerfox                      `
- [ ] `      ` `    20` `mihome-humidifier             `
- [ ] `      ` `    20` `hoymiles-wifi                 `
- [ ] `      ` `    20` `ems-influxdb                  `
- [ ] `   117` `    19` `navimow                       `
- [ ] `      ` `    19` `blink                         `
- [ ] `   119` `    18` `smartvisu                     `
- [ ] `      ` `    18` `kostal-piko-mp-plus           `
- [ ] `      ` `    18` `hptoner                       `
- [ ] `      ` `    18` `e-control-at-fuel             `
- [ ] `   123` `    17` `wizconnect                    `
- [ ] `      ` `    17` `syrconnect                    `
- [ ] `      ` `    17` `openuv                        `
- [ ] `      ` `    17` `meteoblue                     `
- [ ] `      ` `    17` `keyble                        `
- [ ] `      ` `    17` `bluesound                     `
- [ ] `   129` `    16` `vis-knob                      `
- [ ] `      ` `    16` `open-epaper-link              `
- [ ] `      ` `    16` `komoot                        `
- [ ] `      ` `    16` `evsewifi                      `
- [ ] `      ` `    16` `ecb1                          `
- [ ] `      ` `    16` `btc_kurs                      `
- [ ] `   135` `    15` `spritmonitor                  `
- [ ] `      ` `    15` `ryd                           `
- [ ] `      ` `    15` `rpi                           `
- [ ] `      ` `    15` `magentatv                     `
- [ ] `      ` `    15` `checkmk                       `
- [ ] `   140` `    14` `polestar                      `
- [ ] `      ` `    14` `nightscout                    `
- [ ] `      ` `    14` `fully-mqtt                    `
- [ ] `      ` `    14` `epson-esc-vp21                `
- [ ] `      ` `    14` `blauberg-ventilation          `
- [ ] `   145` `    13` `wm-bus                        `
- [ ] `      ` `    13` `surepetcareio                 `
- [ ] `      ` `    13` `netio                         `
- [ ] `      ` `    13` `nello                         `
- [ ] `      ` `    13` `meteoswiss                    `
- [ ] `      ` `    13` `cups                          `
- [ ] `      ` `    13` `admin-2                       `
- [ ] `   152` `    12` `zeptrion                      `
- [ ] `      ` `    12` `paperless-ngx                 `
- [ ] `      ` `    12` `idm                           `
- [ ] `      ` `    12` `homekit2                      `
- [ ] `      ` `    12` `blynk                         `
- [ ] `      ` `    12` `arlo                          `
- [ ] `   158` `    11` `nspanel-lovelace-ui           `
- [ ] `      ` `    11` `minmax                        `
- [ ] `      ` `    11` `epson_xp540                   `
- [ ] `      ` `    11` `co2mini                       `
- [ ] `   162` `    10` `tractive                      `
- [ ] `      ` `    10` `solvis                        `
- [ ] `      ` `    10` `smgd                          `
- [ ] `      ` `    10` `smartstate                    `
- [ ] `      ` `    10` `samsungTizen                  `
- [ ] `      ` `    10` `ntfy                          `
- [ ] `      ` `    10` `meldungsliste                 `
- [ ] `      ` `    10` `ip-symcon                     `
- [ ] `      ` `    10` `iobroker.windhager            `
- [ ] `   171` `     9` `wiserbyfeller                 `
- [ ] `      ` `     9` `vis-2-widgets-weather         `
- [ ] `      ` `     9` `todoist                       `
- [ ] `      ` `     9` `qcells-qhome-ess-hyb-g2       `
- [ ] `      ` `     9` `poolcontroller                `
- [ ] `      ` `     9` `photovoltaikcharts            `
- [ ] `      ` `     9` `mygekko                       `
- [ ] `      ` `     9` `midas-aquatemp                `
- [ ] `      ` `     9` `json2object                   `
- [ ] `      ` `     9` `js2fs-community               `
- [ ] `      ` `     9` `find-my-iphone-community      `
- [ ] `      ` `     9` `espresence                    `
- [ ] `      ` `     9` `cloudless-homeconnect         `
- [ ] `      ` `     9` `artnetdmx                     `
- [ ] `      ` `     9` `airthings-cloud               `
- [ ] `      ` `     9` `admin-beta                    `
- [ ] `   187` `     8` `zabbix                        `
- [ ] `      ` `     8` `timer-switch                  `
- [ ] `      ` `     8` `smarthome_webots              `
- [ ] `      ` `     8` `smartfriends                  `
- [ ] `      ` `     8` `raumfeld                      `
- [ ] `      ` `     8` `powerdog                      `
- [ ] `      ` `     8` `oscam                         `
- [ ] `      ` `     8` `ms-teams                      `
- [ ] `      ` `     8` `lirc                          `
- [ ] `      ` `     8` `kress                         `
- [ ] `      ` `     8` `jsonconfig-demo               `
- [ ] `      ` `     8` `hagelschutz                   `
- [ ] `      ` `     8` `epson_workforce               `
- [ ] `      ` `     8` `chartjs                       `
- [ ] `   201` `     7` `z2m                           `
- [ ] `      ` `     7` `wlanthermo                    `
- [ ] `      ` `     7` `smawebbox                     `
- [ ] `      ` `     7` `smaevcharger                  `
- [ ] `      ` `     7` `samsung2022                   `
- [ ] `      ` `     7` `opensprinkler                 `
- [ ] `      ` `     7` `ochsner-web2com               `
- [ ] `      ` `     7` `iosapp                        `
- [ ] `      ` `     7` `idm-multitalent_002           `
- [ ] `      ` `     7` `dingz                         `
- [ ] `      ` `     7` `device-manager                `
- [ ] `      ` `     7` `bayernluft                    `
- [ ] `   213` `     6` `yandex_smart_home             `
- [ ] `      ` `     6` `wr-delta                      `
- [ ] `      ` `     6` `vw-carnet                     `
- [ ] `      ` `     6` `vis-deepcore                  `
- [ ] `      ` `     6` `time_switch_clock             `
- [ ] `      ` `     6` `sqlstatistics                 `
- [ ] `      ` `     6` `speedtest                     `
- [ ] `      ` `     6` `opnsense                      `
- [ ] `      ` `     6` `mystrom-wifi-button           `
- [ ] `      ` `     6` `hausbusde                     `
- [ ] `      ` `     6` `groupalarm                    `
- [ ] `      ` `     6` `electrolux-aeg                `
- [ ] `      ` `     6` `echarge_cpu2                  `
- [ ] `      ` `     6` `clage-dsx                     `
- [ ] `      ` `     6` `bootstrap4                    `
- [ ] `   228` `     5` `youless                       `
- [ ] `      ` `     5` `wr-goodwe-mt                  `
- [ ] `      ` `     5` `vis-sip-asterisk              `
- [ ] `      ` `     5` `threema-gw                    `
- [ ] `      ` `     5` `stromgedacht                  `
- [ ] `      ` `     5` `stock-market                  `
- [ ] `      ` `     5` `state-mapping                 `
- [ ] `      ` `     5` `signalclirestapiclient        `
- [ ] `      ` `     5` `remotethermo                  `
- [ ] `      ` `     5` `powertrust-storage            `
- [ ] `      ` `     5` `powertrust-cloud              `
- [ ] `      ` `     5` `oura                          `
- [ ] `      ` `     5` `oasecontrol                   `
- [ ] `      ` `     5` `nuc                           `
- [ ] `      ` `     5` `mystrom-wifi-bulb             `
- [ ] `      ` `     5` `miner                         `
- [ ] `      ` `     5` `digitalstrom-vdc              `
- [ ] `      ` `     5` `deyesun                       `
- [ ] `      ` `     5` `boblight                      `
- [ ] `      ` `     5` `awekas-connector              `
- [ ] `      ` `     5` `artnet2                       `
- [ ] `      ` `     5` `arcam                         `
- [ ] `      ` `     5` `Coronavirus Statistics        `
- [ ] `   251` `     4` `wmbus                         `
- [ ] `      ` `     4` `winsipbrowser                 `
- [ ] `      ` `     4` `volkszaehler-api              `
- [ ] `      ` `     4` `voc-monitor                   `
- [ ] `      ` `     4` `vis-2-widgets-sip             `
- [ ] `      ` `     4` `vis-2-widgets-react-template  `
- [ ] `      ` `     4` `vis-2-shelly                  `
- [ ] `      ` `     4` `test                          `
- [ ] `      ` `     4` `tasmota                       `
- [ ] `      ` `     4` `tailscale                     `
- [ ] `      ` `     4` `solax-x1-mini-rs485           `
- [ ] `      ` `     4` `solarmax-iobroker-adapter     `
- [ ] `      ` `     4` `snapcast                      `
- [ ] `      ` `     4` `sky-q                         `
- [ ] `      ` `     4` `sensate                       `
- [ ] `      ` `     4` `rtv                           `
- [ ] `      ` `     4` `roomba-rw                     `
- [ ] `      ` `     4` `primelab                      `
- [ ] `      ` `     4` `pegelonline                   `
- [ ] `      ` `     4` `occ                           `
- [ ] `      ` `     4` `nutriu                        `
- [ ] `      ` `     4` `neeo                          `
- [ ] `      ` `     4` `mymazda                       `
- [ ] `      ` `     4` `my-muell                      `
- [ ] `      ` `     4` `mihome-air                    `
- [ ] `      ` `     4` `i2clcd                        `
- [ ] `      ` `     4` `huawei-charger                `
- [ ] `      ` `     4` `google-home-nest              `
- [ ] `      ` `     4` `fordpass                      `
- [ ] `      ` `     4` `energy-flow-motion            `
- [ ] `      ` `     4` `adapter-studio                `
- [ ] `   282` `     3` `wrapper                       `
- [ ] `      ` `     3` `wifilight-community           `
- [ ] `      ` `     3` `vera                          `
- [ ] `      ` `     3` `valloxserial                  `
- [ ] `      ` `     3` `udmx                          `
- [ ] `      ` `     3` `ubuntu                        `
- [ ] `      ` `     3` `twitch                        `
- [ ] `      ` `     3` `tablet-control                `
- [ ] `      ` `     3` `syncthing                     `
- [ ] `      ` `     3` `steam                         `
- [ ] `      ` `     3` `solar-manager                 `
- [ ] `      ` `     3` `sienna                        `
- [ ] `      ` `     3` `reolink-810a                  `
- [ ] `      ` `     3` `pv-cast                       `
- [ ] `      ` `     3` `otgw                          `
- [ ] `      ` `     3` `oikos-connect                 `
- [ ] `      ` `     3` `oikos-assistant               `
- [ ] `      ` `     3` `ochsner-roomterminal          `
- [ ] `      ` `     3` `mysql                         `
- [ ] `      ` `     3` `mcp3xxx-analog                `
- [ ] `      ` `     3` `lgtv12                        `
- [ ] `      ` `     3` `keenergy                      `
- [ ] `      ` `     3` `kebahp                        `
- [ ] `      ` `     3` `iobapp                        `
- [ ] `      ` `     3` `homekit                       `
- [ ] `      ` `     3` `hid                           `
- [ ] `      ` `     3` `gridradar                     `
- [ ] `      ` `     3` `greensens                     `
- [ ] `      ` `     3` `esvewifi                      `
- [ ] `      ` `     3` `e3dc                          `
- [ ] `      ` `     3` `diashow                       `
- [ ] `      ` `     3` `datentauscher                 `
- [ ] `      ` `     3` `darksky                       `
- [ ] `      ` `     3` `cloudrain                     `
- [ ] `      ` `     3` `chargeamps                    `
- [ ] `      ` `     3` `cec                           `
- [ ] `      ` `     3` `ariston-remotethermo          `
- [ ] `      ` `     3` `admin-neo                     `
- [ ] `   320` `     2` `zoe                           `
- [ ] `      ` `     2` `xmpp                          `
- [ ] `      ` `     2` `wr-goodwe-ht                  `
- [ ] `      ` `     2` `waterkotte                    `
- [ ] `      ` `     2` `watchdog                      `
- [ ] `      ` `     2` `vue                           `
- [ ] `      ` `     2` `vis-powertrust-fonts          `
- [ ] `      ` `     2` `vis-2-widgets-weather_heating `
- [ ] `      ` `     2` `victron-vrm                   `
- [ ] `      ` `     2` `vf-station                    `
- [ ] `      ` `     2` `ventcubecontrol               `
- [ ] `      ` `     2` `vdr                           `
- [ ] `      ` `     2` `v-zug                         `
- [ ] `      ` `     2` `uws                           `
- [ ] `      ` `     2` `unifi-protect-nvr             `
- [ ] `      ` `     2` `trashmaster                   `
- [ ] `      ` `     2` `timecounter                   `
- [ ] `      ` `     2` `template                      `
- [ ] `      ` `     2` `tautulli                      `
- [ ] `      ` `     2` `tasmota-zigbee                `
- [ ] `      ` `     2` `stiebel-lwz                   `
- [ ] `      ` `     2` `speedport_hybrid              `
- [ ] `      ` `     2` `spanet                        `
- [ ] `      ` `     2` `sony-playstation              `
- [ ] `      ` `     2` `solexa2                       `
- [ ] `      ` `     2` `solarlogmail                  `
- [ ] `      ` `     2` `sockethighway                 `
- [ ] `      ` `     2` `smart-race-event-receiver     `
- [ ] `      ` `     2` `smart-me                      `
- [ ] `      ` `     2` `sky-plus-hd                   `
- [ ] `      ` `     2` `shellaction                   `
- [ ] `      ` `     2` `scriptgui                     `
- [ ] `      ` `     2` `sawtooth                      `
- [ ] `      ` `     2` `rikafirenet                   `
- [ ] `      ` `     2` `reanimator                    `
- [ ] `      ` `     2` `realweather                   `
- [ ] `      ` `     2` `presence-simulator            `
- [ ] `      ` `     2` `powertrust-solaredge          `
- [ ] `      ` `     2` `power-off                     `
- [ ] `      ` `     2` `pokeys                        `
- [ ] `      ` `     2` `philips-android-tv            `
- [ ] `      ` `     2` `openinghours                  `
- [ ] `      ` `     2` `openhomecontrol               `
- [ ] `      ` `     2` `onkyo2                        `
- [ ] `      ` `     2` `onkyo-vis                     `
- [ ] `      ` `     2` `nuki-extended-mcc             `
- [ ] `      ` `     2` `nodedmx                       `
- [ ] `      ` `     2` `nextcloud                     `
- [ ] `      ` `     2` `network                       `
- [ ] `      ` `     2` `netpoint                      `
- [ ] `      ` `     2` `mytkstar-gps                  `
- [ ] `      ` `     2` `mysensors-2                   `
- [ ] `      ` `     2` `my-opcua                      `
- [ ] `      ` `     2` `mhi_aircon                    `
- [ ] `      ` `     2` `mcc                           `
- [ ] `      ` `     2` `lacrosse                      `
- [ ] `      ` `     2` `jvc_dila                      `
- [ ] `      ` `     2` `io-box                        `
- [ ] `      ` `     2` `huawei-smartlogger-http       `
- [ ] `      ` `     2` `hkv                           `
- [ ] `      ` `     2` `han                           `
- [ ] `      ` `     2` `hama                          `
- [ ] `      ` `     2` `fullyBrowser                  `
- [ ] `      ` `     2` `fleck-pruefstand              `
- [ ] `      ` `     2` `fitbit                        `
- [ ] `      ` `     2` `firebase                      `
- [ ] `      ` `     2` `example                       `
- [ ] `      ` `     2` `espadapterserver              `
- [ ] `      ` `     2` `elero-over-mediola            `
- [ ] `      ` `     2` `eigene_datenpunkte            `
- [ ] `      ` `     2` `e2-openwebif                  `
- [ ] `      ` `     2` `dmxface                       `
- [ ] `      ` `     2` `devicectrl                    `
- [ ] `      ` `     2` `connect                       `
- [ ] `      ` `     2` `bropcua                       `
- [ ] `      ` `     2` `boschebike                    `
- [ ] `      ` `     2` `bacnet                        `
- [ ] `      ` `     2` `alarmcontrol                  `
- [ ] `      ` `     2` `airquality                    `
- [ ] `      ` `     2` `aduro-stove                   `
